version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models
      - ./.env:/app/.env
    env_file:
      - .env
    networks:
      - cortex-network


networks:
  cortex-network:
    driver: bridge 